# Generated by Django 3.1.2 on 2020-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='tags',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
    ]
