# Generated by Django 3.1.2 on 2020-10-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(choices=[('r', 'Red'), ('b', 'Blue'), ('g', 'Green')], max_length=1)),
            ],
        ),
    ]
